### ISSUE TITLE
Songs Playlist not showing list of songs 

### ISSUE THREAD

**Issue by Raul824** [jellyfin/jellyfin-web#1429]
When adding songs to playlist and old playlists which were showing lists of songs isn't working.
Was working in 10.5.5

The Playlist is having 39 minutes of playback. But it isn't showing any songs.
It was working in 10.5.5 this is not happening to all of the songs but some songs.
I am trying to check the pattern but am unable to pinpoint to the exact root cause of this issue.

![image](https://user-images.githubusercontent.com/51978647/84994175-a41b9e80-b18d-11ea-9289-c4b28adb4502.png)

Docker Debian
Nightly 10.6

i couldn't find the exact but try adding Ennio Morricone's soundtrack CD to check the playlist bug.

**Comment by ferferga** [comment]
@Raul824 Should be fixed in #1430

**Comment by Raul824** [comment]
Let me know how i can help. I can test or else fixed the code as well. Not a pro but having sufficient knowledge of debugging and coding.

**Comment by ferferga** [comment]
@Raul824 Hey, thanks for the interest!

Yes, actually it needs a lot of testing because the player it's a central thing in Jellyfin and it's almost impossible to test every single situation.

Just checkout my PR's branch locally in your system and run yarn install & yarn serve, as stated in the description.

**Comment by Raul824** [comment]
I am now able to see all the songs in queue and playlist
But my playlist folder keeps on loading and never completes loading i have to search the exact name of my playlists to open.

Could you let me know what all bugs were there i will test all open bugs for you and will let you know if any new ones i found.

**Comment by Raul824** [comment]
Downloaded latest nightly image.
Playlist page now loads fine.
The webpage loading has also very fast compared to previous nightly build.

But still unable to see songs in queue.
And playlists names are not coming for the ones which have posters populated in thumbnail.

![image](https://user-images.githubusercontent.com/51978647/86161402-8b799400-bb50-11ea-8418-8f95815774f0.png)

**Comment by ferferga** [comment]
@Raul824 My changes hasn't been merged yet. 

Also, nightly is no longer supported, we're now using ``unstable``
