### ISSUE TITLE
Subtitles dim screen (like video controls do)

### ISSUE THREAD

**Issue by el-tiuri** [jellyfin/jellyfin-web#723]
**Describe the bug**
Video slightly dims as if controls are active when subtitles are on the screen. If no subtitles are on the screen (between dialogue or with subtitles disabled) the video looks like it should.

**To Reproduce**
1. Activate subtitles
2. Play
3. You'll notice the dimming when it goes from no subtitles displayed to when there are, it's not very apparent once it's dimmed

**Expected behavior**
Video remains the same colour throughout playback/only slightly dims when controls are visible.

**Logs**

**Screenshots**
Wasn't apparent on screenshots, I can send a video if that helps

**System (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Safari, Firefox
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Last.fm (3.0.0.0), Open Subtitles (7.0.0.0), Trakt (7.0.0.0)
 - Reverse proxy: no

**Additional context**
Especially visible in dark videos

**Comment by arantes555** [comment]
@el-tiuri I have the same thing on macOS on other video websites. It's only in fullscreen, when no DOM element at all is show except the video. I guess it's a macOS bug, because it is indeed not visible at all in screenshots.

**Comment by arantes555** [comment]
a possible workaround is to always show a 1px*1px div with 1% opacity in a corner

**Comment by anthonylavado** [comment]
@arantes555 What other websites could you see this on? What browser are you using? (I'm our resident macOS expert.)

**Comment by el-tiuri** [comment]
After some digging I found out this is a MacOS issue, and after I realised that I also checked Netflix - same exact thing. Also, this apparently only happens in full screen. I can’t verify that now, since I’m on mobile.

A workaround is  resizing the cursor in accessibility settings, although that only works until the machine shuts down.

**Comment by arantes555** [comment]
@anthonylavado Yep, as el-tiuri said, it happens on all websites with fullscreen video. I use mostly Chrome, not sure if it happens of other browsers though. It's probably the main reason why I never watch video in fullscreen anymore ^^ The most infuriating thing last time I look for a reason, or even a reference to this issue somewhere, is that I could find *nothing* on the internet about it. At least know I know it's not just my machine / video card doing weird stuff.

@el-tiuri which exact model do you have ? It may still have to do with the videocard or something.  I'm on a 15" end-2013 MBP.

**Comment by el-tiuri** [comment]
@arantes555 I have a mid 2014 13" MBP. The same behaviour also occurs on my gf's device (I think a 2017 Macbook Air).

If you search for that issue but you mention Netflix you'll see other people complaining about it. It seems to be a MacOS bug relating to fullscreen video playback. The only workaround I've found (as mentioned in my other comment) is resizing the cursor every time you boot up your computer).

**Comment by el-tiuri** [comment]
@JustAMan sorry, missed your comment. It's an srt file, though I don't think another filetype would not exhibit this behaviour.

**Comment by arantes555** [comment]
This issue is still relevant

**Comment by arantes555** [comment]
The issue is still relevant

**Comment by anthonylavado** [comment]
Screenshot from the demo server for reference:
<img width="640" alt="subs" src="https://user-images.githubusercontent.com/596194/90679318-f9c40400-e22d-11ea-8668-b373285acdaa.png">

- iMac running macOS Catalina 10.15.6 (19G2021)
- Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by anthonylavado** [comment]
Turns out this issue has more information in #1425. Do you folks mind going in there and trying the "Classic" option in the System Preferences?

**Comment by arantes555** [comment]
@anthonylavado I think you misunderstand the issue. It is not about the black box around the subtitles. It's that, when subtitles appear / disappear, the brightness of the whole image changes noticeably.

This issue should not be closed, it has nothing to do with #1425

**Comment by anthonylavado** [comment]
Then I am unable to reproduce the issue. Do you have any extra info you can provide?

- Media details (such as the Media Info dialogue in Jellyfin, which will contain codec and subtitle details)
- macOS Version
- Chrome version

**Comment by arantes555** [comment]
@anthonylavado it has happed for me on every macOS version from 10.13 to 10.15, on every Chrome version for the last few years, with every video.

A few thing to note is that it only happens in fullscreen, only happens when the on-screen controls are hidden, and is much more noticeable on darker scenes. For example, on the Pioneer One episode on the demo.jellyfin.org server, it is very visible at aproximately 3:55, between the lines "Cancer?" and "Cancer is the least of his problems".

Also, as I said in https://github.com/jellyfin/jellyfin-web/issues/723#issuecomment-578237510 , it does not appear to be Jellyfin-specific. However, there is a simple workaround that could be implemented in jellyfin : just constantly showing a 1px*1px div with 1% opacity in a corner.

**Comment by MrTimscampi** [comment]
> Also, as I said in [#723 (comment)](https://github.com/jellyfin/jellyfin-web/issues/723#issuecomment-578237510) , it does not appear to be Jellyfin-specific. However, there is a simple workaround that could be implemented in jellyfin : just constantly showing a 1px*1px div with 1% opacity in a corner.

To the risk of being an asshole: if it happens everywhere and is not a Jellyfin-specific issue, it's not our problem.

Please open a bug on Chrome/Chromium and have them fix it. I'm categorically against the 1px fix, because it's a dirty fix to an upstream problem that should be solved there.

I'll leave this open for discussion a bit, but IMO this is out of our hands and needs to be raised with the Chrome team, not with us.

**Comment by AndrewBreyen** [comment]
Has this been submitted to Chromium as a bug? Still an issue with the latest chrome version. 

Kinda hard to tell, but here's playback in Chrome: https://youtu.be/mFx5JjFbyQY
and using the JF app for mac: https://youtu.be/UOjCywiZnrE

**Comment by dadodasyra** [comment]
This does seems to happen on windows 11 on chrome too.
When subtitles are shown on image in a dim scene it makes the whole screen brighter than when there's none subtitles.
It's subrip subs on sdr content but maybe it's doing it in other cases

**Comment by l3ftb3hind** [comment]
I just experienced this today on my Fire Stick.  Not affecting Android or web via Chromium.  It (for me) is a DVD rip in .mp4 format.  The issue happens when subtitles are supposed to appear.  They are baked in to the .mp4 file and show on Jellyfin as "Default - DVDSUB".  I can give anymore information if needed, as well as a video of it happening if that helps at all 👍

**Comment by unleftie** [comment]
On Netflix, this issue can be fixed by setting the font color to semi-transparent, [see](https://www.reddit.com/r/OLED/comments/un4vnr/fix_netflix_subtitle_brightness_by_doing_this/). I didn't find any similar options on Jellyfin
