### ISSUE TITLE
[Tizen 10.11.0] Jellyfin remuxes instead of direct playing of DV 7.6 with HDR fallback or with HDR+

### ISSUE THREAD

**Issue by dusanhatvani** [jellyfin/jellyfin-web#7231]
### Description of the bug

After upgrading to version 10.11.0 Jellyfin is remuxing content with DV profile 7.6 on my Tizen TV.
Previously on 10.10.7 Jellyfin used to directly play such content with no issues.
In such cases Jellyfin used to utilize either HDR10 fallback or HDR10+ if present.

The main problem is then tied to TRUE HD direct play, which is possible when eARC soundbar is connected to Tizen TV. This forced remuxing breaks the TRUE HD playback. If audio transcoding is enabled, jellyfin transcodes the TRUE HD to AAC. If it is not enabled, TV is reporting TRUE HD audio playback, but no sound comes out.

Similar issue if not the same occured on version 10.9.2 last year 
https://github.com/jellyfin/jellyfin/issues/11794#issue-2310987953

### Reproduction steps

1. Play any 4K remux with DV profile 7.6 with HDR fallback or HDR10+ on Samsung Tizen TV
2. Observe remuxing taking place instead of direct playing.

### What is the current _bug_ behavior?

Remuxing/Transcode instead of direct play

### What is the expected _correct_ behavior?

Jellyfin should detect HDR fallback or present HDR10+ profile and should direct play the file

### Jellyfin Server version

10.10.0+

### Specify the build version

10.11.0

### Environment

```markdown
- OS: Linux
- Virtualization: docker
- Clients: Tizen
```

### Jellyfin logs

```shell
Attached
```

### FFmpeg logs

```shell
Attached
```

### Additional information

[ffmpeg log.txt](https://github.com/user-attachments/files/23014609/ffmpeg.log.txt)
[jellyfin logs.txt](https://github.com/user-attachments/files/23014608/jellyfin.logs.txt)

**Comment by gnattu** [comment]
If you believe it is due to TrueHD:

<img width="834" height="263" alt="Image" src="https://github.com/user-attachments/assets/8783c065-86a8-488b-a79d-8c8e62d765bd" />

But I think it is not. I think we should hardcode the Tizen client profile to set it to support `DOVIWithEL` and `DOVIWithELHdr10Plus`. With current HDR handling, the server will strip the DOVI metadata on the server side to prevent playback issues (because some client player simply crash  or show a black screen with such file). If we can confirm samsung TVs won't be affected by such video, we can safely declare it to support those dovi formats and let the client to handle the fallback instead using the server side workaround.

**Comment by dusanhatvani** [comment]
> If you believe it is due to TrueHD:
> 
> <img alt="Image" width="834" height="263" src="https://private-user-images.githubusercontent.com/12995396/503601562-8783c065-86a8-488b-a79d-8c8e62d765bd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjEwNDI0MDIsIm5iZiI6MTc2MTA0MjEwMiwicGF0aCI6Ii8xMjk5NTM5Ni81MDM2MDE1NjItODc4M2MwNjUtODZhOC00ODhiLWE3OWQtOGM4ZTYyZDc2NWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIxVDEwMjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMThhNzk1NjBjMTQwNDZhN2E2NGM2NWJlOTk2OTVlMjA2YTRkYTU0MjMxYjIzMjRiOThkYmJhNzA4ZDgwODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1oq0BxmDiPX0ZpXT4CnEuaJaodZheu7ALiQHlNpKY_g">
> But I think it is not. I think we should hardcode the Tizen client profile to set it to support `DOVIWithEL` and `DOVIWithELHdr10Plus`. With current HDR handling, the server will strip the DOVI metadata on the server side to prevent playback issues (because some client player simply crash or show a black screen with such file). If we can confirm samsung TVs won't be affected by such video, we can safely declare it to support those dovi formats and let the client to handle the fallback instead using the server side workaround.

It is not due to TrueHD. I tried using compatiblity DD track and it also caused remuxing. My biggest issue is loosing TrueHD due to this remuxing even though there is no reason for Jellyfin to transcode it. 

I agree with the approach to let the client handle the fallback. As I mentioned, all those files were working correctly on previous version 10.10.7. Or make it an option to enable/disable on client's side?

Also one more note. DV profile 8.1 is not problematic

**Comment by tsoulard** [comment]
Looking at the code that was submitted and checking how the https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/browserDeviceProfile.js works along with the changes made for tizen specific use cases https://github.com/jellyfin/jellyfin-web/commits/master/src/scripts/browserDeviceProfile.js is it possible that something else is happening in the flow as it looks like the profile being built wouldn't have changed except for the change to the number of streams supported

**Comment by tsoulard** [comment]
Looking at the logs that @dusanhatvani provided it looks like the number of streams is around 82 if i'm not mistaken so I'm pretty confident that the issue here is related to the change made by @dmitrylyzo in [this MR](https://github.com/jellyfin/jellyfin-web/pull/6537) which i believe was intended to limit the number of streams for older version of tizen but at least in versions 8 and now 9 that limit is no longer present. I think simply adding a version check onto that line should solve the issue for current tizen.


Something like this
```javascript
if (browser.tizen && browser.tizenVersion < 8) {
        // Tizen doesn't support more than 32 streams in a single file
        profile.ContainerProfiles.push({
            Type: 'Video',
            Conditions: [{
                Condition: 'LessThanEqual',
                Property: 'NumStreams',
                Value: '32',
                IsRequired: false
            }]
        });
    }
```

**Comment by dusanhatvani** [comment]
> Looking at the logs that [@dusanhatvani](https://github.com/dusanhatvani) provided it looks like the number of streams is around 82 if i'm not mistaken so I'm pretty confident that the issue here is related to the change made by [@dmitrylyzo](https://github.com/dmitrylyzo) in [this MR](https://github.com/jellyfin/jellyfin-web/pull/6537) which i believe was intended to limit the number of streams for older version of tizen but at least in versions 8 and now 9 that limit is no longer present. I think simply adding a version check onto that line should solve the issue for current tizen.
> 
> Something like this
> 
> if (browser.tizen && browser.tizenVersion < 8) {
>         // Tizen doesn't support more than 32 streams in a single file
>         profile.ContainerProfiles.push({
>             Type: 'Video',
>             Conditions: [{
>                 Condition: 'LessThanEqual',
>                 Property: 'NumStreams',
>                 Value: '32',
>                 IsRequired: false
>             }]
>         });
>     }

I don't think this is it. I quickly wanted to test this by removing most of subtitle streams from one of my mkv files. Unless I did it wrong, reducing number of streams to just 12 did not solve the issue unfortunately.

[ffmpeg log new.txt](https://github.com/user-attachments/files/23031126/ffmpeg.log.new.txt)

**Comment by tsoulard** [comment]
> > Looking at the logs that [@dusanhatvani](https://github.com/dusanhatvani) provided it looks like the number of streams is around 82 if i'm not mistaken so I'm pretty confident that the issue here is related to the change made by [@dmitrylyzo](https://github.com/dmitrylyzo) in [this MR](https://github.com/jellyfin/jellyfin-web/pull/6537) which i believe was intended to limit the number of streams for older version of tizen but at least in versions 8 and now 9 that limit is no longer present. I think simply adding a version check onto that line should solve the issue for current tizen.
> > Something like this
> > if (browser.tizen && browser.tizenVersion < 8) {
> > // Tizen doesn't support more than 32 streams in a single file
> > profile.ContainerProfiles.push({
> > Type: 'Video',
> > Conditions: [{
> > Condition: 'LessThanEqual',
> > Property: 'NumStreams',
> > Value: '32',
> > IsRequired: false
> > }]
> > });
> > }
> 
> I don't think this is it. I quickly wanted to test this by removing most of subtitle streams from one of my mkv files. Unless I did it wrong, reducing number of streams to just 12 did not solve the issue unfortunately.
> 
> [ffmpeg log new.txt](https://github.com/user-attachments/files/23031126/ffmpeg.log.new.txt)

Interestingly i tried the same and It still transcoded but this time there was one less transcode reason.  So i did have a `The number of streams exceeds the limit`  reason as well as `The video's range type is not supported`. but now with the subtitles removed it's just `The video's range type is not supported`.

here are the logs post removal of the subtitles 
[FFmpeg.Transcode.log](https://github.com/user-attachments/files/23031600/FFmpeg.Transcode.log)

**Comment by tsoulard** [comment]
Looks like my case is slightly different but i think as @gnattu suggests hardcoding tizen to support  `DOVIWithEL|DOVIWithELHdr10Plus` as well as also adding `DOVI` will do the trick as well as ammending the number of streams supported in newer versions of Tizen.

**Comment by agneevX** [comment]
This is the same on LG webOS as well. https://github.com/jellyfin/jellyfin-webos/issues/310

**Comment by krishhari2105** [comment]
I played dolby vision profiles 7.6 and 10.1 (AV1) test videos with HDR10 fallback in plex and it direct plays the files in HDR10 if we choose force direct play option in the plex tizen client. We can provide the same option too in our jellyfin clients eliminating the client playback capablity checks by jellyfin before sending streams. may be we could make this option common for all TV clients like webos, tizen , android etc so that it wont break compatablity. Sorry im not a coder, so i dont know whether implementing this could be difficult or not. i just shared my thoughts ...

**Comment by dusanhatvani** [comment]
> I played dolby vision profiles 7.6 and 10.1 (AV1) test videos with HDR10 fallback in plex and it direct plays the files in HDR10 if we choose force direct play option in the plex tizen client. We can provide the same option too in our jellyfin clients eliminating the client playback capablity checks by jellyfin before sending streams. may be we could make this option common for all TV clients like webos, tizen , android etc so that it wont break compatablity. Sorry im not a coder, so i dont know whether implementing this could be difficult or not. i just shared my thoughts ...

Looking at the issues reported through the last few days in various jellyfin repositories, it seems like that all web based clients are affected. And it is not only the DV P7.6. I saw remuxing on DV P8.1 with HDR fallback + EAC3 Atmos, which also used to direct play. The client playback capability checking is flawed thus creating more problems than benefits.  I know that remux is not resource heavy, but it is still more resources than direct play. And it can create problems like mine with forces audio trancode breaking truehd playback on tizen.

Either a rollback of checking the client capabilities or making it an option is really necessary. + the number of stream fix for newer tizen version @tsoulard mentioned above

**Comment by kinke** [comment]
I can confirm that removing the 32-streams-limit as suggested by @tsoulard (thx mate!) works fine on Tizen 9 for me; an .mkv with almost 100 streams (incl. DV P8.1 with HDR10 fallback) now direct-plays again, without remuxing. FWIW, I've used CI to generate a patched v10.11.1 .wgt for me; you can download the artifact from https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18975676507.

I have another .mkv with DV P8.1, but an HDR10+ fallback - that still required remuxing. So I've hacked further, enabling `HDR10Plus|DOVIWithHDR10Plus|DOVIWithELHDR10Plus` on the client side - and I can confirm that this makes that .mkv direct-play now too. Downloadable from https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18977125875.

**Comment by dusanhatvani** [comment]
> I can confirm that removing the 32-streams-limit as suggested by [@tsoulard](https://github.com/tsoulard) (thx mate!) works fine on Tizen 9 for me; an .mkv with almost 100 streams (incl. DV P8.1 with HDR10 fallback) now direct-plays again, without remuxing. FWIW, I've used CI to generate a patched v10.11.1 .wgt for me; you can download the artifact from https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18975676507.
> 
> I have another .mkv with DV P8.1, but an HDR10+ fallback - that still required remuxing. So I've hacked further, enabling `HDR10Plus|DOVIWithHDR10Plus|DOVIWithELHDR10Plus` on the client side - and I can confirm that this makes that .mkv direct-play now too. Downloadable from https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18977125875.

I've tried the second build and it works wonders on one of my files I posted earlier with DOVIWithELHDR10Plus where I removed unneccessary streams. However I am still remuxing / trancoding on most files and I don't understand why. 
Does the second build include also the first fix with the stream limit? Maybe I have older Tizen OS version on my QN90B from 2022. Settings on the TV does not show the version, but in device manager from Tizen Studio I can see platform "tv-6.5". I've had no issues with huge numbers of streams on 10.10.7 on the very same TV. 
Can you please build me a WGT with a condition "if (browser.tizen && browser.tizenVersion < 6)" just for testing? 

You can also enable DOVIWithELHDR10 on the client side in the build. It should be working no problem.
I am also including some ffpmeg logs from your build from the remuxes/transcodes I mentioned. Maybe you'll find out what is wrong.

[ffmpeg 1.txt](https://github.com/user-attachments/files/23267228/ffmpeg.1.txt)
[ffmpeg 2.txt](https://github.com/user-attachments/files/23267229/ffmpeg.2.txt)
[ffmpeg 3.txt](https://github.com/user-attachments/files/23267227/ffmpeg.3.txt)

**Comment by kinke** [comment]
Excellent, thanks for testing, getting closer. Yes the 2nd build included the allow-more-streams fix, but only for Tizen 8+. I've changed it to 6+ now, and also enabled `DOVIWithEL` for DV P7 (as per https://github.com/jellyfin/jellyfin/pull/13277; the name is still like that in server [v10.11.1](https://github.com/jellyfin/jellyfin/blob/v10.11.1/Jellyfin.Data/Enums/VideoRangeType.cs#L51)). Downloadable from https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18981331428.

**Edit**: The total diff: https://github.com/kinke/jellyfin-tizen-builds/blob/master/web.diff

**Comment by dusanhatvani** [comment]
> Excellent, thanks for testing, getting closer. Yes the 2nd build included the allow-more-streams fix, but only for Tizen 8+. I've changed it to 6+ now, and also enabled `DOVIWithEL` for DV P7 (as per [jellyfin/jellyfin#13277](https://github.com/jellyfin/jellyfin/pull/13277); the name is still like that in server [v10.11.1](https://github.com/jellyfin/jellyfin/blob/v10.11.1/Jellyfin.Data/Enums/VideoRangeType.cs#L51)). Downloadable from https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18981331428.
> 
> **Edit**: The total diff: https://github.com/kinke/jellyfin-tizen-builds/blob/master/web.diff

The man, the myth, the legend! :)

Everything is direct playing again as it should be. Only one DV P8.1 DD+ 5.1 file is still being remuxed. Maybe because of included mov_text subtitles? I am including the logs 

Edit: ok I looked at another file with DDP+ DV8.1 with mov_text included and it was direct playing. The difference is the file format. MP4 is being remuxed and MKV is direct playing

[ffmpeg remux.txt](https://github.com/user-attachments/files/23269001/ffmpeg.remux.txt)

**Comment by kinke** [comment]
Nice! - Wrt. that one .mp4 container: what stood out to my untrained eye in your log is that the video stream is apparently anamorphic (`"IsAnamorphic":true`), incl. ffmpeg's (note the `SAR 48755:48756`):
> `Stream 0:0[0x2](eng): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3824x1592 [SAR 1:1 DAR 478:199], 24397 kb/s, SAR 48755:48756 DAR 245:102, 23.98 fps, 23.98 tbr, 16k tbn (default)`

And that seems to violate a requirement in https://github.com/jellyfin/jellyfin-web/blob/de2fe3f52d3e6469ba8f2da1fb151fdbd444022b/src/scripts/browserDeviceProfile.js#L1247-L1253 - although it sounds weird to me that a remux would be enough (**edit**: or required) to support that unchanged anamorphic stream...

**Comment by dusanhatvani** [comment]
I converted the anamorphic file into mkv and now it direct plays.

Also I found one more problamatic file type that used to direct play on previous version 10.10.7.
This is very specific DV profile 8.6 that is used in Game of Thrones for example. Jellyfin recognizes it as DOVIInvalid.

<img width="1797" height="1323" alt="Image" src="https://github.com/user-attachments/assets/5822cce3-1695-44ba-94d7-8cc031b266f2" />

[ffmpeg DOVIInvalid.txt](https://github.com/user-attachments/files/23281595/ffmpeg.DOVIInvalid.txt)

**Comment by gnattu** [comment]
> This is very specific DV profile 8.6 that is used in Game of Thrones for example. Jellyfin recognizes it as DOVIInvalid.

Because 8.6 is indeed out of Dolby Vision Spec and is technically invalid. This profile may crash the real Dolby Vision compliant players and that is why the server will force removing all Dolby Vision metadata which requires a remux. For Tizen as Dolby vision is not supported anyway, I think declare DO VIInvalid is also safe for most of cases

**Comment by kinke** [comment]
Okay, I can try to enable `DOVIInvalid` too then later.

Wrt. anamorphic-ness, I think there's a bug in the server there, after finding a supposedly anamorphic .mp4 in my samples collection too, which annoyingly gets remuxed:
```
$ ffprobe hevc_4K60P_bilibili_pq_4.mp4
ffprobe version 7.1.2-0+deb13u1+rpt2 Copyright (c) 2007-2025 the FFmpeg developers
[…]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'hevc_4K60P_bilibili_pq_4.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.24.101
    description     : Bilibili VXCode Swarm Transcoder v0.3.77
  Duration: 00:04:32.37, start: 0.000000, bitrate: 11269 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160, 11131 kb/s, 60 fps, 60 tbr, 16k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
```

This file doesn't seem to specify a SAR (samples aspect ratio) nor a DAR (display AR) at all, making Jellyfin treat it as anamorphic in https://github.com/jellyfin/jellyfin/blob/40a33da2a5354df0060eb18e89ceb348c9775e30/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L855-L884 AFAICT - null/empty AR strings seem to always make it anamorphic, plus in https://github.com/jellyfin/jellyfin/blob/40a33da2a5354df0060eb18e89ceb348c9775e30/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L572-L584, the special `0:1` strings seem to be normalized to an empty string earlier.

Additionally, it looks like the computed and originally-specified AR are compared string-wise, which I think should end up comparing a computed (and minimally rounded) `2.40:1` (see [here](https://github.com/jellyfin/jellyfin/blob/v10.11.1/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L1135)) to  the original `478:199` for the file in https://github.com/jellyfin/jellyfin-web/issues/7231#issuecomment-3474685133.

**Comment by kinke** [comment]
> Okay, I can try to enable DOVIInvalid too then later.

https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18997580231

**Comment by dusanhatvani** [comment]
> > Okay, I can try to enable DOVIInvalid too then later.
> 
> https://github.com/kinke/jellyfin-tizen-builds/actions/runs/18997580231

DV 8.6 (DOVIInvalid) files direct playing once again. Thank you

**Comment by kinke** [comment]
Cool, thx for testing. I guess we have enough info for a proper PR now - but hopefully someone else can cover that. :)

I got slightly fed up with the cumbersomeness of displaying interesting media details in the Tizen app:
* 'Media info' is unusable (only showing the first few rows without a way to scroll down AFAIK)
* 'Playback info' lacks some IMO interesting stats (like the `VideoRangeType`, which supports/displays HDR10+, unlike the `VideoDoViTitle` currently; then also frame rate, color space, pixel format...), and is cumbersome to toggle on/off in the settings menu.

So I've hacked further, adding a few stats to the playback info, and making that overlay easily toggle-able in the player footer directly, as additional info icon right next to the settings icon. If anyone else is interested: https://github.com/kinke/jellyfin-tizen-builds/actions/runs/19000825301

**Edit**: I'd actually also be interested in the max nits stats (in VLC: max luminance, MaxCLL, MaxFALL), but that probably requires an API change to include that data if available.

**Comment by dusanhatvani** [comment]
> So I've hacked further, adding a few stats to the playback info, and making that overlay easily toggle-able in the player footer directly, as additional info icon right next to the settings icon. If anyone else is interested: https://github.com/kinke/jellyfin-tizen-builds/actions/runs/19000825301

Really nice change

**Comment by kinke** [comment]
Okay, PRs created, incl. the proposed playback/media info tweaks (#7285, #7286, #7287).

**Comment by krishhari2105** [comment]
> Okay, PRs created, incl. the proposed playback/media info tweaks ([#7285](https://github.com/jellyfin/jellyfin-web/pull/7285), [#7286](https://github.com/jellyfin/jellyfin-web/pull/7286), [#7287](https://github.com/jellyfin/jellyfin-web/pull/7287)).

I think your DOVI HDR fallback PR #7284  didnt include av1VideoRangeTypes += '|DOVIWithHDR10 & av1VideoRangeTypes += '|DOVIWithHDR10Plus , thats for Profile 10.1. i know 10.1 is not widely available but will be needed in future...could you look at your commit once?

**Comment by kinke** [comment]
Adding support for DV profile 10 would be an addition, not a regression fix for v10.11 - so I think that should be done in another PR, targeting the master branch. After a quick look, I think this DV handling could use a refactoring, e.g., returning `[7, 8]` in `supportedDolbyVisionProfilesHevc()` for Tizen (note that P5 - `DOVI` without fallback - is excluded), and also returning truthy for Tizen in `supportedDolbyVisionProfileAv1()` (to populate `av1VideoRangeTypes` - but not with fallback-less `DOVI` for Tizen).

**Edit**: Actually, it may be best to merge both functions to a single `supportedDolbyVisionProfiles()`, and returning `[7, 8, 10]` (and 9?) on Tizen. And then populating `hevcVideoRangeTypes` and `av1VideoRangeTypes` accordingly.

**Comment by kinke** [comment]
The 2 remuxing regressions are fixed now in branch `release-10.11.z`, after #7298 (which also enabled DV profile 10) and #7283.

Wrt. anamorphic-ness, turns out that the *enforced* remuxing actually [breaks](https://github.com/jellyfin/jellyfin-tizen/issues/376) the aspect ratio, while direct-playing anamorphic videos works just fine for me at least: #7321

My latest .wgt build in https://github.com/kinke/jellyfin-tizen-builds/actions/runs/19249269345 is based on `release-10.11.z` from some minutes ago, and additionally includes:
* #7321 (but enabled for Tizen in general, to test older versions too)
* #7291 (incl. remuxing reasons!)
* #7285
* #7287

So far, the only remaining remuxing reason I've seen on Tizen 9 is a selected secondary audio track, which really requires it (otherwise the first track is played, regardless of selection): https://github.com/jellyfin/jellyfin-web/blob/39f971ffa4fe0f2b76d3b0dc0619b957c46483a1/src/scripts/browserDeviceProfile.js#L467-L469

**Comment by dusanhatvani** [comment]
> My latest .wgt build in https://github.com/kinke/jellyfin-tizen-builds/actions/runs/19249269345 is based on `release-10.11.z` from some minutes ago, and additionally includes:
> 
> * [Tizen: Enable direct-play of anamorphic videos #7321](https://github.com/jellyfin/jellyfin-web/pull/7321) (but enabled for Tizen in general, to test older versions too)
> * [Compact the "playback info" overlay to add more infos #7291](https://github.com/jellyfin/jellyfin-web/pull/7291) (incl. remuxing reasons!)
> * [Playback info: Promote out of settings menu to OSD footer icon #7285](https://github.com/jellyfin/jellyfin-web/pull/7285)
> * [Media info dialog: Shrink font size on TV to work around non-scrollability #7287](https://github.com/jellyfin/jellyfin-web/pull/7287)

Tested and working flawlessly

**Comment by kinke** [comment]
> Tested and working flawlessly

Incl. testing anamorphic videos on your Tizen 6.5 TV, confirming that the aspect ratio is applied correctly?

**Comment by dusanhatvani** [comment]
> > Tested and working flawlessly
> 
> Incl. testing anamorphic videos on your Tizen 6.5 TV, confirming that the aspect ratio is applied correctly?

I don't have that anamorphic file anymore. Wife decided she did not like the movie, so it had to go :)
I can redownload it for testing if you want to. Should I keep it in mp4 format which will force remuxing? In mkv container it was direct playing with no issues. And if I remember correctly, even when it was remuxing back then, the aspect ratio looked fine.

**Comment by kinke** [comment]
IIRC, your file wasn't really anamorphic; ffmpeg remuxing only seems to have made it so. So I think you'd need some actual anamorphic video to be able to judge whether the aspect ratio is correctly applied.

**Comment by dusanhatvani** [comment]
When I inspected the file with media info, jellyfin stated it was anamorphic. 

Anyway I downloaded some sample anamorphic video, but it was direct playing with no issues. 
If you can provide me some sample file to test with Tizen 6.5, I will happily do so.

**Comment by kinke** [comment]
I've looked for some publicly available samples, but couldn't find any. Here are 2 samples I've uploaded (incl. people for easy judging whether the AR is okay), and should be available for about 3 days:
* https://temp.sh/fwgye/Invasion.mkv (720x472 => 873x472; **edit**: should almost occupy full TV area for 1.85:1, with tiny horizontal black bars)
  ```
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 720x472 [SAR 40:33 DAR 1200:649], SAR 97:80 DAR 873:472, 23.98 fps, 23.98 tbr, 1k tbn (default)
  ```
* https://temp.sh/xjwQO/At_The_Bar.mkv (720x576 => 1024x576; **edit**: should occupy full 16:9 TV area)
  ```
    Stream #0:0: Video: h264 (High), yuv420p(tv, smpte170m/bt470bg/bt709, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
  ```

**Comment by dusanhatvani** [comment]
Both samples are direct playing for me with correct aspect ratio

**Comment by kinke** [comment]
Perfect, thx for testing, #7321 updated accordingly.

Btw, on my hunt for samples earlier I've found and tested some Dolby Vision Profile 10 (AV1) sample with HDR10+ fallback - works flawlessly for me. :+1:

**Comment by Bambus3000** [comment]
Both your samples and my troublesome tv-show episodes are playing as they should on my 2021 QN95A with Tizen 6.0. :)

**Comment by krishhari2105** [comment]
> Perfect, thx for testing, [#7321](https://github.com/jellyfin/jellyfin-web/pull/7321) updated accordingly.
> 
> Btw, on my hunt for samples earlier I've found and tested some Dolby Vision Profile 10 (AV1) sample with HDR10+ fallback - works flawlessly for me. 👍

Huge thanks for your contributions, also Tizen TVs support native ac-4 playback but current jellyfin implementation supports only transcoding for 5.1ch ac4 files. https://github.com/jellyfin/jellyfin-androidtv/issues/4666#issuecomment-2908060308 as per this issue in android TV branch he says we need to add a function that checks client support for ac4 codec and enable it in directplay list. Also i dont know if this should be enabed in the server side too.I tried but couldnt find the logic since im not a coder. If you are free can you look into this if anything possibly can be done?

**Comment by kinke** [comment]
Okay, wrt. AC-4 support: #7329. Let's keep that topic there please. :)
