### ISSUE TITLE
Noto Sans font incorrectly displays backtick/grave as a combining character 

### ISSUE THREAD

**Issue by JustAPerson** [jellyfin/jellyfin-web#997]
**Describe the bug**
The Noto Sans font will combine a backtick/grave mark (U+0060) as if it had been a combining accent instead (U+0300).

**To Reproduce**
1. In the search bar, paste the following 
  ```
  `w`h`a`t
  ```
2. See that it has been transformed into combining accent marks

**Expected behavior**
The backticks/graves would NOT be combined

**Screenshots**
![2020-03-28_08:32:31_316x135](https://user-images.githubusercontent.com/789308/77823116-2df82600-70cf-11ea-8e10-61a8efadca70.png)

**System (please complete the following information):**
 - OS: Ubuntu 18.04 on server and client using firefox
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.0

**Additional context**
Seems like this is a well known problem with Noto Sans
https://github.com/googlefonts/noto-fonts/issues/736
https://github.com/google/fonts/issues/2202
https://www.reddit.com/r/redesign/comments/87cr1f/the_tilde_and_the_backtick_symbol_dont_show/
https://www.reddit.com/r/redesign/comments/8jul8h/the_font_really_needs_to_be_changed_from_noto_sans/

**Comment by Artiume** [comment]
@dkanada I believe this is fixed, right?

**Comment by MrTimscampi** [comment]
The original issue is indeed fixed in https://github.com/jellyfin/jellyfin-plugin-anime/pull/62

The \` character isn't meant to be used by itself, so in normal cases, what Noto does is the expected behavior, I believe.

**Comment by Artiume** [comment]
I see, just tried it out. It's odd, it doesn't provide any width space for the back tick. You can type ten back ticks together and they stack on top of each other.

**Comment by MrTimscampi** [comment]
> I see, just tried it out. It's odd, it doesn't provide any width space for the backtick. You can type ten backticks together and they stack on top of each other.

That's because the "grave" character (Somewhat incorrectly called a backtick) is not a proper character by itself, in typography.

You will never see \` by itself, except in code.

Its purpose is to be used as a accent on characters in some languages. For example \` + e = è.

**Comment by Artiume** [comment]
Interesting. So most fonts that give grave whitespace, are they correct or wrong? What's the solution here?

**Comment by JustAPerson** [comment]
> The ` character isn't meant to be used by itself, so in normal cases, what Noto does is the expected behavior, I believe.

What? Noto sans is basically the only font that behaves this way.

> That's because the "grave" character (Somewhat incorrectly called a backtick) is not a proper character by itself, in typography.

Maybe in some ivory tower academic sense. That's not at all how the real world works however.

> For example ` + e = è.

That is only true under certain specific operating system IME settings. That's not how ASCII or Unicode work.

**Comment by JustAPerson** [comment]
> What's the solution here?

Seems like updating Noto Sans according to [this comment](https://www.reddit.com/r/redesign/comments/87cr1f/the_tilde_and_the_backtick_symbol_dont_show/dwcz5w3/)

Works as expected here if you type some sample text
https://fonts.adobe.com/fonts/noto-sans

**Comment by MrTimscampi** [comment]
I can assure you that I'm not using any IME and, when typing \` + e on an AZERTY Belgian keyboard, è is what's output.

I actually need to specifically type \`\` to get the standalone character.

In any case, @ferferga 's update to the font handling for 10.6 should fix this, then, but the AniDB specific issue is already fixed.

**Comment by ferferga** [comment]
@JustAPerson As @MrTimscampi said, this is how it looks with my latest PR:

![photo_2020-04-21_18-55-05](https://user-images.githubusercontent.com/10274099/79891759-bc777300-8401-11ea-8f26-71229de517fd.jpg)

So I think it's a matter for it to be merged. The PRs as a reference: jellyfin/jellyfin#2871, #1087 and jellyfin/jellyfin-android#312

**Comment by ferferga** [comment]
Just noticed that this is still present on the **subsetted** version of the new jjellyfin-noto distribution schema, I'll take a look at it.

**Comment by mateon1** [comment]
This seems to have returned. This seems to affect all sans serif text on github, including issue/PR text and textboxes as well as the search bar.
This makes writing issues with code blocks really difficult, since you can't tell where the backticks got placed.

**Comment by thornbill** [comment]
I can no longer reproduce this
